SAHAM_BIG = [
    "BBRI","BMRI","BBCA","BBNI","BRIS",
    "TLKM","ASII","ICBP","INDF","CPIN",
    "ADRO","PTBA","ANTM","MDKA","MEDC"
]
SAHAM_MID = [
    "BRPT","TPIA","ERAA","ACES","MAPI",
    "EXCL","ISAT","GOTO","BUKA","TKIM",
    "INKP","SMRA","PWON","BSDE","CTRA",
    "ELSA","ESSA","HEAL","MIKA","SILO",
    "BTPS","ARTO","BJBR","BJTM","BBTN",
    "SCMA","TBIG","AKRA","DOID","DEWA",
    "INDY","LSIP","DSNG","ULTJ","MYOR",
    "WOOD","MARK","MTDL","SRTG","EMTK",
    "ARCI","TOBA","COAL","HILL","IPCC"
]
SAHAM_SMALL = [
    "BIPI","BELL","ATLA","DEPO","WIFI",
    "MNCN","KPIG","PANI","NICL","NCKL",
    "FILM","RAJA","ENRG","BOSS","ZINC",
    "BRMS","BUMI","APEX","IPTV","DGIK",
    "OKAS","PACK","PPRE","SAME","CARE",
    "HOMI","WEHA","SAFE","DATA","JAST",
    "MGRO","PSGO","SICO","IMPC","MLBI",
    "ROTI","CMRY","CLEO","CUAN","BBKP",
    "BBMD","CARS","CENT","DEAL","EDGE",
    "KINO","PICO","AGII","BBYB","MTDL",
    "SRTG","EMTK","ARCI","TOBA","COAL"
]
SAHAM_ALL = SAHAM_BIG + SAHAM_MID + SAHAM_SMALL
